name: Scrape Data
on:
  workflow_dispatch:
  schedule:
    - cron:  '1,31 23,0,11,12 * * *' # Every 12 hours. Ref https://crontab.guru/examples.html
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - name: script
      run: ./masterScript.sh
      shell: bash
    - name: Commit report
      run: |
          git config --global user.name 'lukaskorba-indiedev'
          git config --global user.email 'lukaskorba-indiedev@users.noreply.github.com'
          git add -A
          git commit -am "Automated report"
          git push
